### ISSUE TITLE
cant compile after following instructions

### ISSUE THREAD

**Issue by Brendacg616** [gbr1/ros_openvino#1]
I have already used Openvino with Intel Nural Computer Stick and tested it with some samples. But when i tried to build your package, it has a trouble in the link part of the object detection node

...
...
...
[ 96%] Built target filter_base
/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/lib/intel64/libinference_engine.so: undefined reference to `tbb::interface7::internal::task_arena_base::internal_max_concurrency(tbb::interface7::task_arena const*)'
collect2: error: ld returned 1 exit status
ros_openvino/CMakeFiles/object_detection.dir/build.make:130: recipe for target '/home/bot/catkin_ws/devel/lib/ros_openvino/object_detection' failed
make[2]: *** [/home/bot/catkin_ws/devel/lib/ros_openvino/object_detection] Error 1
CMakeFiles/Makefile2:6936: recipe for target 'ros_openvino/CMakeFiles/object_detection.dir/all' failed
make[1]: *** [ros_openvino/CMakeFiles/object_detection.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 96%] Built target urg_node_driver
[ 96%] Built target navsat_transform_node
[ 96%] Built target ukf
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gbr1** [comment]
Hi @Brendacg616! Thank you for interesting in my package!
it seems that problems is here:<br>
`/opt/intel/openvino_2019.1.094/deployment_tools/inference_engine/lib/intel64/libinference_engine.so: undefined reference to tbb::interface7::internal::task_arena_base::internal_max_concurrency(tbb::interface7::task_arena const*)'`<br>
<br>
Can you say more about system you are using?<br>
At the moment this package has been tested on ROS Kinetic Kame on Ubuntu 16.04 on x86_64 platform.  Tested OpenVINO versions are 5 and 5.1
<br>
Can you try to build putting only this package in your workspace source folder?
<br>
Let me know!  I will try to help you.

**Comment by gbr1** [comment]
@Brendacg616 just installed everything from scratch. I think I need to update my wiki instruction because now it is easier.
My setup:
- UP2 Atom E3950
- Ubuntu 16.04.5
- devices: NCS, Ai Core, Ai Core X
- ROS kinetic kame

<br>

I suggest you to follow this guide:
[NCS2 getting started](https://software.intel.com/en-us/articles/get-started-with-neural-compute-stick)
When you arrive to this step:<br>
`./install_GUI.sh`<br>
run it with **sudo** , it allows you to install OpenVINO in ***/opt/intel***<br>
Don't forget to put:
`source /opt/intel/openvino/bin/setupvars.sh`<br>
in your .bashrc file
<br>
After you have done this steps, just clone this repo e do catkin_make.
<br>
Let me know if it solves your issues.
<br>

**Comment by gbr1** [comment]
@Brendacg616 just updated the wiki: https://github.com/gbr1/ros_openvino/wiki/Fast-setup-for-Myriad-based-devices 
These steps are fully tested and working.
